baseUrl = "https://htr3n.github.io/"
languageCode = "en"

author = "htr3n"
title = "htr3n's"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

theme = "hyde-hyde"

## Hugo Built-in Features
disqusShortname = "https-htr3n-github-io" # Comment out to disable Disqus.
googleAnalytics = "UA-112764962-1"
enableRobotsTXT = true
enableEmoji = true

# Built-in highlighting
# https://gohugo.io/content-management/syntax-highlighting
#pygmentsCodeFences = true
#pygmentsStyle = "friendly"
#pygmentsStyle = "monokai"
#pygmentsStyle = "default"
#pygmentsUseClasses = true     # this overrides 'PygmentsStyle'
#http://pygments.org
#pygmentsUseClassic = true     # falling back to Pygments instead of Chroma

## Site Settings
[params]
    author = "htr3n"
    description = "technology, thoughts, opinions, rants"
    authorimage = "img/avatar.png"

    # https://golang.org/pkg/time/#example_Time_Format
    dateformat = "Jan 2, 2006"

    # https://highlightjs.org
    highlightjs = true
    #highlightjsstyle = "agate"
    #highlightjsstyle = "androidstudio"
    #highlightjsstyle = "atom-one-dark"
    highlightjsstyle = "atom-one-light"
    #highlightjsstyle = "dracula"
    #highlightjsstyle = "darcula"
    #highlightjsstyle = "github"
    #highlightjsstyle = "hybrid"
    #highlightjsstyle = "monokai"
    #highlightjsstyle = "ocean"
    #highlightjsstyle = "railscasts"
    #highlightjsstyle = "rainbow"
    #highlightjsstyle = "sunburst"
    #highlightjsstyle = "tomorrow-night"
    #highlightjsstyle = "tomorrow-night-bright"
    #highlightjsstyle = "tomorrow-night-eighties"
    #highlightjsstyle = "zenburn"

    # either GraphComment or Disqus
    # https://graphcomment.com
    #GraphCommentId = "htr3n-github-io"

    mainSections = ["post"]
[permalinks]
    posts = "/:year/:month/:slug/"
    vn = "/:year/:month/:slug/"

## Site Meta Settings
[params.meta]
    description = "htr3n's blog :: technology, thoughts, opinions, and rants"
    keywords = "blog,java,php,python,golang,javascript,shell,thoughts,macos,apple,tiếng việt,parental,family,apache,httpd,laravel,politics,critical thinking,chính trị,luật,hiến pháp,xã hội,gia đình"

## Social Accounts
[params.social]
    github = "htr3n"
    #instagram = "htr3n"
    medium = "htr3n"
    #bitbucket = "hoanghuytran"
    linkedin = "htr3n"
    twitter = "htr3n"
    keybase = "htr3n"
    #facebook = "htr3n"
    #gitlab = "htr3n"
    #stackoverflow = "339302"
    #xing = "Huy_Tran2"
    email = "hoang.huy.tran+blog@gmail.com"


## Main Menu
[[menu.main]]
    name = "Writing"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 300
    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 900
    url = "/about/"
[[menu.main]]
    name = "Tiếng Việt"
    identifier = "vn"
    weight = 800
    url = "/vn/"

# https://gohugo.io/content-management/related
[related]
    # Only include matches with rank >= threshold. This is a normalized rank
    # between 0 and 100.
    threshold = 80
    # To get stable "See also" sections we, by default, exclude newer related
    # pages.
    includeNewer = false
    # Will lower case keywords in both queries and in the indexes.
    toLower = false
[[related.indices]]
    name = "keywords"
    weight = 150
[[related.indices]]
    name  = "author"
    toLower = true
    weight = 30
[[related.indices]]
    name  = "tags"
    weight = 100
[[related.indices]]
    name  = "date"
    weight = 10
    pattern = "2006"
