baseUrl = "https://htr3n.github.io"
languageCode = "en"

author = "htr3n"
title = "htr3n's"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

theme = "hyde-hyde"

## Hugo Built-in Features
disqusShortname = "https-htr3n-github-io" # Comment out to disable Disqus.
googleAnalytics = "UA-112764962-1"
enableRobotsTXT = true
enableEmoji = true

## Site Settings
[params]
    author = "htr3n"
    description = "technology, thoughts, opinions, rants"
    authorimage = "/img/avatar.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    #highlightjsstyle = "agate"
    #highlightjsstyle = "rainbow"
    #highlightjsstyle = "atom-one-dark"
    #highlightjsstyle = "ocean"
    #highlightjsstyle = "tomorrow-night-eighties"
    highlightjsstyle = "zenburn"
    #highlightjsstyle = "androidstudio"
    #highlightjsstyle = "railscasts"
    #PygmentsCodeFences = true
    #PygmentsStyle = "friendly"
    #PygmentsUseClasses = true
    #GraphCommentId = "htr3n-github-io" # please choose either GraphComment or Disqus
    mainSections = ["post"]
[permalinks]
    posts = "/:year/:month/:slug/"
    vn = "/:year/:month/:slug/"

## Site Meta Settings
[params.meta]
    description = "htr3n's blog :: technology, opinions, and rants about everything"
    keywords = "blog,java,php,python,golang,javascript,shell,thoughts,macos,apple,tiếng việt,parental,family,apache,httpd,laravel,politics,critical thinking,chính trị,luật,hiến pháp,xã hội,gia đình"

## Social Accounts
[params.social]
    github = "htr3n"
    #instagram = "htr3n"
    #medium = "htr3n"
    bitbucket = "hoanghuytran"
    linkedin = "htr3n"
    twitter = "htr3n"
    #facebook = "htr3n"
    gitlab = "htr3n"
    stackoverflow = "339302"
    #xing = "Huy_Tran2"
    email = "hoang.huy.tran+blog@gmail.com"


## Main Menu
[[menu.main]]
    name = "Articles"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 300
    url = "/portfolio/"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 900
    url = "/about/"
[[menu.main]]
    name = "Tiếng Việt"
    identifier = "vn"
    weight = 800
    url = "/vn/"

# https://gohugo.io/content-management/related
[related]
# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 80
# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = false
# Will lower case keywords in both queries and in the indexes.
toLower = false
[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name  = "author"
toLower = true
weight = 30
[[related.indices]]
name  = "tags"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"